# Generated by Django 5.1.6 on 2025-02-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mof_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='GENRE',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('sci-fi', 'Sci-Fi'), ('romance', 'Romance')], default='default', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
