# Generated by Django 5.1.6 on 2025-02-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mof_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usr_prof',
            name='Role',
        ),
        migrations.AddField(
            model_name='usr_prof',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='default', max_length=10),
            preserve_default=False,
        ),
    ]
