# Generated by Django 5.1.6 on 2025-02-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mof_app', '0003_alter_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Preproduction', 'Preproduction'), ('Shooting', 'Shooting'), ('Postproduction', 'Postproduction'), ('Promotions', 'Promotions')], max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='mof_app.movie')),
            ],
        ),
    ]
